# config.yaml
openai_api_key: 
anthropic_api_key: 

embedding_model:
  type: "openai"  # options: openai, huggingface
  model_name: "text-embedding-3-large"

# embedding_model:
#   type: "huggingface"
#   model_name: "Alibaba-NLP/gte-large-en-v1.5"
#   trust_remote_code: true

chunk_size: 512
